name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Lean
      uses: leanprover/lean-action@v1
    - name: Build Test
      id: build-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Grep Check
        command: "! grep -E \"(sorry|axiom)\" ./Problems/Problems.lean"
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BUILD-TEST_RESULTS: "${{steps.build-test.outputs.result}}"
      with:
        runners: build-test
